apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${spring.application.name}
  name: ${spring.application.name}
spec:
  replicas: ${deployment.replicas}
  selector:
    matchLabels:
      app: ${spring.application.name}
  template:
    metadata:
      labels:
        app: ${spring.application.name}
        api-key-secured: ${api.key.secured}
      annotations:
        timestamp: ${timestamp}
    spec:
      serviceAccountName: default
      containers:
        - name: ${spring.application.name}
          image: "localhost/${project.id}/${project.artifactId}:${git.commit.id.describe}"
          livenessProbe:
            httpGet:
              path: ${spring.servlet.context-path}/actuator/liveness
              port: ${spring.application.port}
            initialDelaySeconds: 80
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: ${spring.servlet.context-path}/actuator/health
              port: ${spring.application.port}
            initialDelaySeconds: 40
            timeoutSeconds: 5
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: "-Djava.security.egd=file:/dev/./urandom "
            - name: SPRING_APPLICATION_NAME
              value: ${spring.application.name}