apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: netflixingress
  namespace: netflix
spec:
  rules:
    - host: netflix.local
      http:
        paths:
            - path:
              backend:
                serviceName: netflix-app
                servicePort: 80